/**
 * generated by Xtext 2.10.0
 */
package co.gruposaberes.model.ui.contentassist;

import co.gruposaberes.model.ui.contentassist.AbstractRailsSchemaProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class RailsSchemaProposalProvider extends AbstractRailsSchemaProposalProvider {
}
