/**
 * generated by Xtext 2.10.0
 */
package co.gruposaberes.model.railsSchema.impl;

import co.gruposaberes.model.railsSchema.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class RailsSchemaFactoryImpl extends EFactoryImpl implements RailsSchemaFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static RailsSchemaFactory init()
  {
    try
    {
      RailsSchemaFactory theRailsSchemaFactory = (RailsSchemaFactory)EPackage.Registry.INSTANCE.getEFactory(RailsSchemaPackage.eNS_URI);
      if (theRailsSchemaFactory != null)
      {
        return theRailsSchemaFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new RailsSchemaFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RailsSchemaFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case RailsSchemaPackage.SCHEMA: return createSchema();
      case RailsSchemaPackage.SCHEMA_MEMBER: return createSchemaMember();
      case RailsSchemaPackage.TABLE: return createTable();
      case RailsSchemaPackage.TABLE_ATTRIBUTES: return createTableAttributes();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Schema createSchema()
  {
    SchemaImpl schema = new SchemaImpl();
    return schema;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SchemaMember createSchemaMember()
  {
    SchemaMemberImpl schemaMember = new SchemaMemberImpl();
    return schemaMember;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Table createTable()
  {
    TableImpl table = new TableImpl();
    return table;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TableAttributes createTableAttributes()
  {
    TableAttributesImpl tableAttributes = new TableAttributesImpl();
    return tableAttributes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RailsSchemaPackage getRailsSchemaPackage()
  {
    return (RailsSchemaPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static RailsSchemaPackage getPackage()
  {
    return RailsSchemaPackage.eINSTANCE;
  }

} //RailsSchemaFactoryImpl
