<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="universal" nsURI="http://universal" nsPrefix="un">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eSubpackages name="core" nsURI="http://universal/core" nsPrefix="unco">
    <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="measurant" eType="#//metrics/Measurement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SimpleElement" eSuperTypes="#//core/Element"/>
    <eClassifiers xsi:type="ecore:EClass" name="Container" eSuperTypes="#//core/Element">
      <eStructuralFeatures xsi:type="ecore:EReference" name="innerElements" upperBound="-1"
          eType="#//core/Element" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Relation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
          eType="#//core/Element"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="#//core/Element"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="measurant" eType="#//metrics/Measurement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RelationContainer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="relations" upperBound="-1"
          eType="#//core/Relation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Application">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="basicElements" lowerBound="1"
          upperBound="-1" eType="#//core/Element" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="complexRelationships"
          upperBound="-1" eType="#//core/RelationContainer" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="simpleRelationships"
          upperBound="-1" eType="#//core/Relation" containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="metrics" nsURI="http://universal/metrics" nsPrefix="unmet">
    <eClassifiers xsi:type="ecore:EClass" name="Measurement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="elmentMeasurants" upperBound="-1"
          eType="#//core/Element"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="relationMeasurants" upperBound="-1"
          eType="#//core/Element"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="measure" upperBound="-1"
          eType="#//metrics/Measure"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Grade" eSuperTypes="#//metrics/Measurement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="gradeValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DimensionalMeasurement" eSuperTypes="#//metrics/Measurement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dimensionValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DimensionalToObjectMeasurement" eSuperTypes="#//metrics/DimensionalMeasurement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Measure">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SimplifiedDecisionMetrics">
      <eStructuralFeatures xsi:type="ecore:EReference" name="measures" upperBound="-1"
          eType="#//metrics/Measure" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="observations" upperBound="-1"
          eType="#//metrics/Observations" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Observations">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="whenObserved" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="measurement" upperBound="-1"
          eType="#//metrics/Measurement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NumberLinesMeasure" eSuperTypes="#//metrics/Measure">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalLines" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="oracleforms" nsURI="http://universal/oracleforms" nsPrefix="unforms">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="Form" eSuperTypes="#//core/SimpleElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Entity Classes"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Table" eSuperTypes="#//core/SimpleElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Module" eSuperTypes="#//core/Container">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="moduleInnerElementsRule"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="moduleInnerElementsRule" value="self.innerElements->forAll(el |&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;el.oclIsTypeOf(Form) = true or el.oclIsTypeOf(Table) = true)"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OracleFormsApp" eSuperTypes="#//core/Application">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="oracleAppRule_MustModule"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="oracleAppRule_MustModule" value="self.basicElements->forAll(md | md.oclIsTypeOf(Module)=true)"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModuleRelationship" eSuperTypes="#//core/Relation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Relation Classes"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="moduleRealtionshiRuel_SourceMustBeModule moduleRealtionshiRuel_TargetsMustBeModule"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="moduleRealtionshiRuel_SourceMustBeModule" value="self.source.oclIsTypeOf(Module) = true"/>
        <details key="moduleRealtionshiRuel_TargetsMustBeModule" value="self.target.oclIsTypeOf(Module) = true"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FormCallRelationship" eSuperTypes="#//core/Relation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="formCallRelationshipRule_SourceMustBeForm formCallRelationshipRule_TargetsMustBeForms"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="formCallRelationshipRule_SourceMustBeForm" value="self.source->forAll(mod | mod.oclIsTypeOf(Form) = true)"/>
        <details key="formCallRelationshipRule_TargetsMustBeForms" value="self.target.oclIsTypeOf(Form) = true"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MasterDetailRelationship" eSuperTypes="#//core/RelationContainer">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="masterDetailRelationshipRule_LimitRelations masterDetailRelationshipRule_FirstMustBeSingleTableRelationship masterDetailRelationshipRule_SegundMustBeSingleTableRelationship"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="masterDetailRelationshipRule_LimitRelations" value="self.relations->size() = 2"/>
        <details key="masterDetailRelationshipRule_FirstMustBeSingleTableRelationship"
            value="self.relations->first().oclIsTypeOf(SingleTableRelationship) = true"/>
        <details key="masterDetailRelationshipRule_SegundMustBeSingleTableRelationship"
            value="self.relations->last().oclIsTypeOf(DetailTableRelationship) = true"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DetailTableRelationship" eSuperTypes="#//core/Relation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="DetailTableRelationshipRule_SourceMustBeTable DetailTableRelationshipRule_TargetsMustBeTable"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="DetailTableRelationshipRule_SourceMustBeTable" value="self.source.oclIsTypeOf(Table) = true"/>
        <details key="DetailTableRelationshipRule_TargetsMustBeTable" value="self.target.oclIsTypeOf(Table) = true"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SingleTableRelationship" eSuperTypes="#//core/Relation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="singleTableRelationshipRule_SourceMustBeForm singleTableRelationshipRule_TargetsMustBeTable"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="singleTableRelationshipRule_SourceMustBeForm" value="self.source.oclIsTypeOf(Form) = true"/>
        <details key="singleTableRelationshipRule_TargetsMustBeTable" value="self.target.oclIsTypeOf(Table) = true"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PLSQLRelationship" eSuperTypes="#//core/Relation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="plsqlRelationshipRule_SourceMustBeForm plsqlRelationshipRule_TargetsMustBeTable"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="plsqlRelationshipRule_SourceMustBeForm" value="self.source.oclIsTypeOf(Form) = true"/>
        <details key="plsqlRelationshipRule_TargetsMustBeTable" value="self.target.oclIsTypeOf(Table) = true"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NumberOfFormsPerModuleMeasure" eSuperTypes="#//metrics/Measure"/>
  </eSubpackages>
  <eSubpackages name="OOP" nsURI="http://universal/oop" nsPrefix="unoop">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="Method" eSuperTypes="#//core/SimpleElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Core Classes"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Type" eSuperTypes="#//core/Container">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="TypeRule_MustContaintMethod"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="TypeRule_MustContaintMethod" value="self.innerElements->forAll(mt | mt.oclIsTypeOf(Method) = true)"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="#//OOP/Type"/>
    <eClassifiers xsi:type="ecore:EClass" name="Interface" eSuperTypes="#//OOP/Type"/>
    <eClassifiers xsi:type="ecore:EClass" name="OOPApplication" eSuperTypes="#//core/Application">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="OOPApplication_MustContaintTypes"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="OOPApplication_MustContaintTypes" value="self.basicElements->forAll(el | el.oclIsTypeOf(Type) = true)"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TypeRelationship" eSuperTypes="#//core/Relation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Relation Classes"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="typeRelationshipRule_SourceMustBeType typeRelationshipRule_TargetsMustBeTypes"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="typeRelationshipRule_SourceMustBeType" value="self.source.oclIsKindOf(Type) = true"/>
        <details key="typeRelationshipRule_TargetsMustBeTypes" value="self.target.oclIsKindOf(Type) = true"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Generalization" eSuperTypes="#//OOP/TypeRelationship"/>
    <eClassifiers xsi:type="ecore:EClass" name="Realization" eSuperTypes="#//OOP/TypeRelationship"/>
    <eClassifiers xsi:type="ecore:EClass" name="Composition" eSuperTypes="#//OOP/TypeRelationship"/>
    <eClassifiers xsi:type="ecore:EClass" name="Dependency" eSuperTypes="#//OOP/TypeRelationship">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="DependencyRule_SourceClassMustBeType DependencyRule_TargetClassMustBeType DependencyRule_MethodInvoked DependencyRule_MethodInvoker"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="DependencyRule_SourceClassMustBeType" value="self.source.oclIsTypeOf(Type) = true"/>
        <details key="DependencyRule_TargetClassMustBeType" value="self.target.oclIsTypeOf(Type) = true"/>
        <details key="DependencyRule_MethodInvoked" value="self.methodInvokedFromSourceClass.oclIsTypeOf(Method) = true"/>
        <details key="DependencyRule_MethodInvoker" value="self.methodInvokerFromTargetClass.oclIsTypeOf(Method) = true"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="methodInvokedFromSourceClass"
          lowerBound="1" eType="#//OOP/Method"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="methodInvokerFromTargetClass"
          lowerBound="1" eType="#//OOP/Method"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WeigthedMethodsPerClassMeasure" eSuperTypes="#//metrics/Measure">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Metrics Classes"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NumberOfClassesMeasure" eSuperTypes="#//metrics/Measure"/>
    <eClassifiers xsi:type="ecore:EClass" name="CouplingBetweenObjectMeasure" eSuperTypes="#//metrics/Measure"/>
    <eClassifiers xsi:type="ecore:EClass" name="NumberOfUsesMeasure" eSuperTypes="#//metrics/Measure"/>
    <eClassifiers xsi:type="ecore:EClass" name="CalculatedCouplingMeasure" eSuperTypes="#//metrics/Measure"/>
    <eClassifiers xsi:type="ecore:EClass" name="NumberOfContainmentsMeasure" eSuperTypes="#//metrics/Measure"/>
  </eSubpackages>
  <eSubpackages name="microservice" nsURI="http://universal/microservice" nsPrefix="unmicro">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="SessionToEntityCluster" eSuperTypes="#//core/SimpleElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Core Classes"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfTypes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfLines" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeReferences" ordered="false"
          upperBound="-1" eType="#//OOP/Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Microservice" eSuperTypes="#//core/Container">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="MicroserviceRule_MustContaintClusters"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="MicroserviceRule_MustContaintClusters" value="self.innerElements->forAll(cluster | cluster.oclIsTypeOf(SessionToEntityCluster) = true)"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MicroserviceArchitecture" eSuperTypes="#//core/Application">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="MicroserviceArchitectureRule_MustMicroserviceElements"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="MicroserviceArchitectureRule_MustMicroserviceElements" value="self.basicElements->forAll(mc | mc.oclIsTypeOf(Microservice) = true or mc.oclIsKindOf(universal::OOP::Type) = true)"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ClusterRelationship" eSuperTypes="#//core/Relation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Relation Classes"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="clusterRelationshipRule_SourceMustBeCluster clusterRelationshipRule_TargetsMustBeClusters"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="clusterRelationshipRule_SourceMustBeCluster" value="self.source.oclIsTypeOf(SessionToEntityCluster) = true"/>
        <details key="clusterRelationshipRule_TargetsMustBeClusters" value="self.target.oclIsTypeOf(SessionToEntityCluster) = true"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="typesContainedLeft" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="typesContainedRight"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MicroserviceRelationship" eSuperTypes="#//core/Relation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="microserviceRelationshipRule_SourceMustBeMicroservice microserviceRelationshipRule_TargetsMustBeMicroservices"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="microserviceRelationshipRule_SourceMustBeMicroservice" value="self.source.oclIsTypeOf(Microservice) = true"/>
        <details key="microserviceRelationshipRule_TargetsMustBeMicroservices" value="self.target.oclIsTypeOf(Microservice) = true"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dependencies" ordered="false"
          upperBound="-1" eType="#//OOP/Dependency"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ClusterRelationConflictPercentageMeasure"
        eSuperTypes="#//metrics/Measure">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Metrics Classes"/>
      </eAnnotations>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="visualization" nsURI="http://universal/visualization" nsPrefix="unvi">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="VDiagramElement" eSuperTypes="#//core/Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="--- Core Classes"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="uuid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="label" eType="#//visualization/VLabel"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="border" eType="#//visualization/VBorder"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VLabel">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="font" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isBold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isItalic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="alignment" eType="#//visualization/Alignment"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" eType="#//visualization/Position"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VDrawable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="#//visualization/Color"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="thickness" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VBorder" eSuperTypes="#//visualization/VDrawable"/>
    <eClassifiers xsi:type="ecore:EClass" name="VContainer" eSuperTypes="#//visualization/VDiagramElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="--- Containers"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elements" ordered="false"
          upperBound="-1" eType="#//visualization/VDiagramElement">
        <eAnnotations source="http://www.eclipse.org/OCL/Collection">
          <details key="nullFree" value="false"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VDiagram" eSuperTypes="#//visualization/VContainer">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRoot" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VClass" eSuperTypes="#//visualization/VContainer">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isShared" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VPackage" eSuperTypes="#//visualization/VContainer"/>
    <eClassifiers xsi:type="ecore:EClass" name="VShape" eSuperTypes="#//visualization/VDiagramElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Charts"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="#//visualization/Color"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="heigth" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VCircule" eSuperTypes="#//visualization/VShape"/>
    <eClassifiers xsi:type="ecore:EClass" name="VTriangle" eSuperTypes="#//visualization/VShape"/>
    <eClassifiers xsi:type="ecore:EClass" name="VDiamond" eSuperTypes="#//visualization/VShape"/>
    <eClassifiers xsi:type="ecore:EClass" name="VQuadrangle" eSuperTypes="#//visualization/VShape"/>
    <eClassifiers xsi:type="ecore:EClass" name="VDot" eSuperTypes="#//visualization/VShape"/>
    <eClassifiers xsi:type="ecore:EClass" name="VEllipse" eSuperTypes="#//visualization/VShape"/>
    <eClassifiers xsi:type="ecore:EClass" name="VRelationInvocation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Relation Classes"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="methodName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VInvocation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="fromMethod" eType="#//visualization/VRelationInvocation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="toMethod" eType="#//visualization/VRelationInvocation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VConnectorElement" eSuperTypes="#//visualization/VDrawable #//core/Relation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="vConnectElementRule_SourceMustBeVDiagramElement vConnectElementRule_TargetMustBeVDiagramElement"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="vConnectElementRule_SourceMustBeVDiagramElement" value="self.source.oclIsTypeOf(VDiagramElement) = true"/>
        <details key="vConnectElementRule_TargetMustBeVDiagramElement" value="self.target.oclIsTypeOf(VDiagramElement) = true"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineType" eType="#//visualization/LineType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="routingType" eType="#//visualization/RoutingType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="arrowTypeForSource" eType="#//visualization/ArrowType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="arrowTypeForTarget" eType="#//visualization/ArrowType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="invocations" eType="#//visualization/VInvocation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="connectors" eType="#//visualization/VDiagramElement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VGeneralization" eSuperTypes="#//visualization/VConnectorElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="VImplements" eSuperTypes="#//visualization/VConnectorElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="VDependecy" eSuperTypes="#//visualization/VConnectorElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="VAssociation" eSuperTypes="#//visualization/VConnectorElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="VAgregation" eSuperTypes="#//visualization/VConnectorElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="VComposition" eSuperTypes="#//visualization/VConnectorElement"/>
    <eClassifiers xsi:type="ecore:EEnum" name="Color">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Enums"/>
      </eAnnotations>
      <eLiterals name="white"/>
      <eLiterals name="black" value="1"/>
      <eLiterals name="blue" value="2"/>
      <eLiterals name="chocolate" value="3"/>
      <eLiterals name="gray" value="4"/>
      <eLiterals name="green" value="5"/>
      <eLiterals name="orange" value="6"/>
      <eLiterals name="purple" value="7"/>
      <eLiterals name="red" value="8"/>
      <eLiterals name="yellow" value="9"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Alignment">
      <eLiterals name="CENTER"/>
      <eLiterals name="LEFT" value="1"/>
      <eLiterals name="RIGHT" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Position">
      <eLiterals name="BORDER"/>
      <eLiterals name="NODE" value="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="LineType">
      <eLiterals name="STRING"/>
      <eLiterals name="STROKE" value="1"/>
      <eLiterals name="POINTS" value="2"/>
      <eLiterals name="MIXED" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="RoutingType">
      <eLiterals name="DIRECT"/>
      <eLiterals name="RECTILINEAL" value="1"/>
      <eLiterals name="TREE" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ArrowType">
      <eLiterals name="NONE"/>
      <eLiterals name="SIMPLE" value="1"/>
      <eLiterals name="TRIANGULAR" value="2"/>
      <eLiterals name="TRIANGULAR_FILLED" value="3"/>
      <eLiterals name="DIAMOND" value="4"/>
      <eLiterals name="DIAMOND_FILLED" value="5"/>
      <eLiterals name="ARROW_DIAMOND" value="6"/>
      <eLiterals name="ARROW_DIAMOND_FILLED" value="7"/>
      <eLiterals name="MANY" value="8"/>
      <eLiterals name="MANY_TRIANGULAR" value="9"/>
      <eLiterals name="MANY_FILLED" value="10"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="rails" nsURI="http://universal/rails" nsPrefix="unmet">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="Application" eSuperTypes="#//core/Application">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="simpleRelationShipsInvariant basicElementsInvariant"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="simpleRelationShipsInvariant" value="self.simpleRelationships->forAll(e | e.oclIsTypeOf(Association)=true)"/>
        <details key="basicElementsInvariant" value="self.basicElements->forAll(&#xA;       &#x9;&#x9;&#x9;e | e.oclIsTypeOf(Method)=true or e.oclIsTypeOf(Attribute)=true or e.oclIsTypeOf(RubyClass)=true or e.oclIsTypeOf(Namespace)=true  &#x9;&#x9;&#x9;&#xA;       &#x9;&#x9;)"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Association" eSuperTypes="#//core/Relation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="associationTypeInvariant sourceInvariant targetInvariant"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="associationTypeInvariant" value="self.associationType = null or &#xA;&#x9;&#x9;&#x9;&#x9;self.associationType = 'M2M' or self.associationType = 'O2M' or self.associationType = 'O2O'"/>
        <details key="sourceInvariant" value="self.source.oclIsTypeOf(RubyClass)=true"/>
        <details key="targetInvariant" value="self.target.oclIsTypeOf(RubyClass)=true"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="associationType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="foreignKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Namespace" eSuperTypes="#//core/Container">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="innerElementsInvariant"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="innerElementsInvariant" value="self.innerElements->forAll(&#xA;&#x9;&#x9;&#x9;&#x9;e|e.oclIsTypeOf(RubyClass)=true or e.oclIsTypeOf(Namespace)=true&#xA;&#x9;&#x9;&#x9;)"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RubyClass" eSuperTypes="#//core/Container">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="innerElementsInvariant"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="innerElementsInvariant" value="self.innerElements->forAll(&#xA;&#x9;&#x9;&#x9;&#x9;e|e.oclIsTypeOf(Method)=true or e.oclIsTypeOf(Attribute)=true&#xA;&#x9;&#x9;&#x9;)"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="superClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Method" eSuperTypes="#//core/SimpleElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="methodTypeInvariant"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="methodTypeInvariant" value="self.methodType = 'instance' or self.methodType = 'class'"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="methodType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//core/SimpleElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
