/*
 * generated by Xtext 2.10.0
 */
package co.gruposaberes.model.parser.antlr;

import co.gruposaberes.model.parser.antlr.internal.InternalRailsSchemaParser;
import co.gruposaberes.model.services.RailsSchemaGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class RailsSchemaParser extends AbstractAntlrParser {

	@Inject
	private RailsSchemaGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_BS", "RULE_SPACE", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRailsSchemaParser createParser(XtextTokenStream stream) {
		return new InternalRailsSchemaParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Schema";
	}

	public RailsSchemaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RailsSchemaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
