/*
 * generated by Xtext 2.10.0
 */
package co.gruposaberes.model


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RailsSchemaStandaloneSetup extends RailsSchemaStandaloneSetupGenerated {

	def static void doSetup() {
		new RailsSchemaStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
