/**
 * generated by Xtext 2.10.0
 */
package co.gruposaberes.model.validation;

import co.gruposaberes.model.validation.AbstractRailsSchemaValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class RailsSchemaValidator extends AbstractRailsSchemaValidator {
}
