/*
 * generated by Xtext 2.10.0
 */
package co.gruposaberes.rails.parser.parser.antlr;

import co.gruposaberes.rails.parser.parser.antlr.internal.InternalSchemaParser;
import co.gruposaberes.rails.parser.services.SchemaGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SchemaParser extends AbstractAntlrParser {

	@Inject
	private SchemaGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_BS", "RULE_SPACE", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSchemaParser createParser(XtextTokenStream stream) {
		return new InternalSchemaParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Schema";
	}

	public SchemaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SchemaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
