/*
 * generated by Xtext
 */
package co.gruposaberes.model.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import co.gruposaberes.model.ui.internal.RailsActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RailsExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return RailsActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return RailsActivator.getInstance().getInjector(RailsActivator.CO_GRUPOSABERES_MODEL_RAILS);
	}
	
}
