/**
 * generated by Xtext 2.10.0
 */
package co.gruposaberes.rails.parser;

import co.gruposaberes.rails.parser.SchemaStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SchemaStandaloneSetup extends SchemaStandaloneSetupGenerated {
  public static void doSetup() {
    SchemaStandaloneSetup _schemaStandaloneSetup = new SchemaStandaloneSetup();
    _schemaStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
