/**
 * generated by Xtext 2.10.0
 */
package co.gruposaberes.rails.parser.schema.impl;

import co.gruposaberes.rails.parser.schema.SchemaMember;
import co.gruposaberes.rails.parser.schema.SchemaPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Member</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SchemaMemberImpl extends MinimalEObjectImpl.Container implements SchemaMember
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SchemaMemberImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SchemaPackage.Literals.SCHEMA_MEMBER;
  }

} //SchemaMemberImpl
