/*
 * generated by Xtext
 */
package co.gruposaberes.model.ui.contentassist

import co.gruposaberes.model.ui.contentassist.AbstractRailsProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class RailsProposalProvider extends AbstractRailsProposalProvider {
}
