/*
 * generated by Xtext 2.10.0
 */
package co.gruposaberes.rails.parser


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SchemaRuntimeModule extends AbstractSchemaRuntimeModule {
}
