/**
 * generated by Xtext 2.10.0
 */
package co.gruposaberes.rails.parser.schema;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Schema</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.gruposaberes.rails.parser.schema.Schema#getSchema_members <em>Schema members</em>}</li>
 * </ul>
 *
 * @see co.gruposaberes.rails.parser.schema.SchemaPackage#getSchema()
 * @model
 * @generated
 */
public interface Schema extends EObject
{
  /**
   * Returns the value of the '<em><b>Schema members</b></em>' containment reference list.
   * The list contents are of type {@link co.gruposaberes.rails.parser.schema.SchemaMember}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Schema members</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Schema members</em>' containment reference list.
   * @see co.gruposaberes.rails.parser.schema.SchemaPackage#getSchema_Schema_members()
   * @model containment="true"
   * @generated
   */
  EList<SchemaMember> getSchema_members();

} // Schema
