/**
 * generated by Xtext 2.10.0
 */
package co.gruposaberes.rails.parser.schema;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see co.gruposaberes.rails.parser.schema.SchemaFactory
 * @model kind="package"
 * @generated
 */
public interface SchemaPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "schema";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.gruposaberes.co/rails/parser/Schema";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "schema";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SchemaPackage eINSTANCE = co.gruposaberes.rails.parser.schema.impl.SchemaPackageImpl.init();

  /**
   * The meta object id for the '{@link co.gruposaberes.rails.parser.schema.impl.SchemaImpl <em>Schema</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.gruposaberes.rails.parser.schema.impl.SchemaImpl
   * @see co.gruposaberes.rails.parser.schema.impl.SchemaPackageImpl#getSchema()
   * @generated
   */
  int SCHEMA = 0;

  /**
   * The feature id for the '<em><b>Schema members</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEMA__SCHEMA_MEMBERS = 0;

  /**
   * The number of structural features of the '<em>Schema</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEMA_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link co.gruposaberes.rails.parser.schema.impl.SchemaMemberImpl <em>Member</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.gruposaberes.rails.parser.schema.impl.SchemaMemberImpl
   * @see co.gruposaberes.rails.parser.schema.impl.SchemaPackageImpl#getSchemaMember()
   * @generated
   */
  int SCHEMA_MEMBER = 1;

  /**
   * The number of structural features of the '<em>Member</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEMA_MEMBER_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link co.gruposaberes.rails.parser.schema.impl.TableImpl <em>Table</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.gruposaberes.rails.parser.schema.impl.TableImpl
   * @see co.gruposaberes.rails.parser.schema.impl.SchemaPackageImpl#getTable()
   * @generated
   */
  int TABLE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE__NAME = SCHEMA_MEMBER_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE__ATTRIBUTES = SCHEMA_MEMBER_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Table</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_FEATURE_COUNT = SCHEMA_MEMBER_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link co.gruposaberes.rails.parser.schema.impl.TableAttributesImpl <em>Table Attributes</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.gruposaberes.rails.parser.schema.impl.TableAttributesImpl
   * @see co.gruposaberes.rails.parser.schema.impl.SchemaPackageImpl#getTableAttributes()
   * @generated
   */
  int TABLE_ATTRIBUTES = 3;

  /**
   * The feature id for the '<em><b>Datatype</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_ATTRIBUTES__DATATYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_ATTRIBUTES__NAME = 1;

  /**
   * The number of structural features of the '<em>Table Attributes</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_ATTRIBUTES_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link co.gruposaberes.rails.parser.schema.Schema <em>Schema</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Schema</em>'.
   * @see co.gruposaberes.rails.parser.schema.Schema
   * @generated
   */
  EClass getSchema();

  /**
   * Returns the meta object for the containment reference list '{@link co.gruposaberes.rails.parser.schema.Schema#getSchema_members <em>Schema members</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Schema members</em>'.
   * @see co.gruposaberes.rails.parser.schema.Schema#getSchema_members()
   * @see #getSchema()
   * @generated
   */
  EReference getSchema_Schema_members();

  /**
   * Returns the meta object for class '{@link co.gruposaberes.rails.parser.schema.SchemaMember <em>Member</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Member</em>'.
   * @see co.gruposaberes.rails.parser.schema.SchemaMember
   * @generated
   */
  EClass getSchemaMember();

  /**
   * Returns the meta object for class '{@link co.gruposaberes.rails.parser.schema.Table <em>Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Table</em>'.
   * @see co.gruposaberes.rails.parser.schema.Table
   * @generated
   */
  EClass getTable();

  /**
   * Returns the meta object for the attribute '{@link co.gruposaberes.rails.parser.schema.Table#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see co.gruposaberes.rails.parser.schema.Table#getName()
   * @see #getTable()
   * @generated
   */
  EAttribute getTable_Name();

  /**
   * Returns the meta object for the containment reference list '{@link co.gruposaberes.rails.parser.schema.Table#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributes</em>'.
   * @see co.gruposaberes.rails.parser.schema.Table#getAttributes()
   * @see #getTable()
   * @generated
   */
  EReference getTable_Attributes();

  /**
   * Returns the meta object for class '{@link co.gruposaberes.rails.parser.schema.TableAttributes <em>Table Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Table Attributes</em>'.
   * @see co.gruposaberes.rails.parser.schema.TableAttributes
   * @generated
   */
  EClass getTableAttributes();

  /**
   * Returns the meta object for the attribute '{@link co.gruposaberes.rails.parser.schema.TableAttributes#getDatatype <em>Datatype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Datatype</em>'.
   * @see co.gruposaberes.rails.parser.schema.TableAttributes#getDatatype()
   * @see #getTableAttributes()
   * @generated
   */
  EAttribute getTableAttributes_Datatype();

  /**
   * Returns the meta object for the attribute '{@link co.gruposaberes.rails.parser.schema.TableAttributes#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see co.gruposaberes.rails.parser.schema.TableAttributes#getName()
   * @see #getTableAttributes()
   * @generated
   */
  EAttribute getTableAttributes_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SchemaFactory getSchemaFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link co.gruposaberes.rails.parser.schema.impl.SchemaImpl <em>Schema</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.gruposaberes.rails.parser.schema.impl.SchemaImpl
     * @see co.gruposaberes.rails.parser.schema.impl.SchemaPackageImpl#getSchema()
     * @generated
     */
    EClass SCHEMA = eINSTANCE.getSchema();

    /**
     * The meta object literal for the '<em><b>Schema members</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCHEMA__SCHEMA_MEMBERS = eINSTANCE.getSchema_Schema_members();

    /**
     * The meta object literal for the '{@link co.gruposaberes.rails.parser.schema.impl.SchemaMemberImpl <em>Member</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.gruposaberes.rails.parser.schema.impl.SchemaMemberImpl
     * @see co.gruposaberes.rails.parser.schema.impl.SchemaPackageImpl#getSchemaMember()
     * @generated
     */
    EClass SCHEMA_MEMBER = eINSTANCE.getSchemaMember();

    /**
     * The meta object literal for the '{@link co.gruposaberes.rails.parser.schema.impl.TableImpl <em>Table</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.gruposaberes.rails.parser.schema.impl.TableImpl
     * @see co.gruposaberes.rails.parser.schema.impl.SchemaPackageImpl#getTable()
     * @generated
     */
    EClass TABLE = eINSTANCE.getTable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TABLE__NAME = eINSTANCE.getTable_Name();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TABLE__ATTRIBUTES = eINSTANCE.getTable_Attributes();

    /**
     * The meta object literal for the '{@link co.gruposaberes.rails.parser.schema.impl.TableAttributesImpl <em>Table Attributes</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.gruposaberes.rails.parser.schema.impl.TableAttributesImpl
     * @see co.gruposaberes.rails.parser.schema.impl.SchemaPackageImpl#getTableAttributes()
     * @generated
     */
    EClass TABLE_ATTRIBUTES = eINSTANCE.getTableAttributes();

    /**
     * The meta object literal for the '<em><b>Datatype</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TABLE_ATTRIBUTES__DATATYPE = eINSTANCE.getTableAttributes_Datatype();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TABLE_ATTRIBUTES__NAME = eINSTANCE.getTableAttributes_Name();

  }

} //SchemaPackage
