/*
 * generated by Xtext
 */
package co.gruposaberes.model;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RailsRuntimeModule extends co.gruposaberes.model.AbstractRailsRuntimeModule {

}
