/*
* generated by Xtext
*/
package co.gruposaberes.model;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class RailsStandaloneSetup extends RailsStandaloneSetupGenerated{

	public static void doSetup() {
		new RailsStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

