/**
 * generated by Xtext
 */
package co.gruposaberes.model.validation;

import co.gruposaberes.model.validation.AbstractRailsValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class RailsValidator extends AbstractRailsValidator {
}
