/**
 * generated by Xtext 2.10.0
 */
package co.gruposaberes.model.railsSchema;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Schema Member</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see co.gruposaberes.model.railsSchema.RailsSchemaPackage#getSchemaMember()
 * @model
 * @generated
 */
public interface SchemaMember extends EObject
{
} // SchemaMember
