/**
 * generated by Xtext 2.10.0
 */
package co.gruposaberes.model.railsSchema;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Table</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.gruposaberes.model.railsSchema.Table#getName <em>Name</em>}</li>
 *   <li>{@link co.gruposaberes.model.railsSchema.Table#getAttributes <em>Attributes</em>}</li>
 * </ul>
 *
 * @see co.gruposaberes.model.railsSchema.RailsSchemaPackage#getTable()
 * @model
 * @generated
 */
public interface Table extends SchemaMember
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see co.gruposaberes.model.railsSchema.RailsSchemaPackage#getTable_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link co.gruposaberes.model.railsSchema.Table#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
   * The list contents are of type {@link co.gruposaberes.model.railsSchema.TableAttributes}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Attributes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference list.
   * @see co.gruposaberes.model.railsSchema.RailsSchemaPackage#getTable_Attributes()
   * @model containment="true"
   * @generated
   */
  EList<TableAttributes> getAttributes();

} // Table
