/**
 * generated by Xtext 2.10.0
 */
package co.gruposaberes.model.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class RailsSchemaDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
