/**
 * generated by Xtext 2.10.0
 */
package co.gruposaberes.rails.parser.models.impl;

import co.gruposaberes.rails.parser.models.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class ModelsFactoryImpl extends EFactoryImpl implements ModelsFactory
{
  /**
	 * Creates the default factory implementation.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public static ModelsFactory init()
  {
		try {
			ModelsFactory theModelsFactory = (ModelsFactory)EPackage.Registry.INSTANCE.getEFactory(ModelsPackage.eNS_URI);
			if (theModelsFactory != null) {
				return theModelsFactory;
			}
		}
		catch (Exception exception) {
			EcorePlugin.INSTANCE.log(exception);
		}
		return new ModelsFactoryImpl();
	}

  /**
	 * Creates an instance of the factory.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public ModelsFactoryImpl()
  {
		super();
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public EObject create(EClass eClass)
  {
		switch (eClass.getClassifierID()) {
			case ModelsPackage.APPLICATION: return createApplication();
			case ModelsPackage.RUBY_CLASS: return createRubyClass();
			case ModelsPackage.CLASS_ELEMENT: return createClassElement();
			case ModelsPackage.TABLE_NAME: return createTableName();
			case ModelsPackage.RELATIONSHIP: return createRelationship();
			case ModelsPackage.HASH_KEY_VALUE: return createHashKeyValue();
			case ModelsPackage.RUBY_METHOD: return createRubyMethod();
			default:
				throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
		}
	}

  /**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Application createApplication() {
		ApplicationImpl application = new ApplicationImpl();
		return application;
	}

		/**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public RubyClass createRubyClass()
  {
		RubyClassImpl rubyClass = new RubyClassImpl();
		return rubyClass;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public ClassElement createClassElement()
  {
		ClassElementImpl classElement = new ClassElementImpl();
		return classElement;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public TableName createTableName()
  {
		TableNameImpl tableName = new TableNameImpl();
		return tableName;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public Relationship createRelationship()
  {
		RelationshipImpl relationship = new RelationshipImpl();
		return relationship;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public HashKeyValue createHashKeyValue()
  {
		HashKeyValueImpl hashKeyValue = new HashKeyValueImpl();
		return hashKeyValue;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public RubyMethod createRubyMethod()
  {
		RubyMethodImpl rubyMethod = new RubyMethodImpl();
		return rubyMethod;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public ModelsPackage getModelsPackage()
  {
		return (ModelsPackage)getEPackage();
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @deprecated
	 * @generated
	 */
  @Deprecated
  public static ModelsPackage getPackage()
  {
		return ModelsPackage.eINSTANCE;
	}

} //ModelsFactoryImpl
