/**
 * generated by Xtext 2.10.0
 */
package co.gruposaberes.rails.parser.models.impl;

import co.gruposaberes.rails.parser.models.ModelsPackage;
import co.gruposaberes.rails.parser.models.TableName;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Table Name</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TableNameImpl extends ClassElementImpl implements TableName
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TableNameImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ModelsPackage.Literals.TABLE_NAME;
  }

} //TableNameImpl
