<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="railsTarget" nsURI="http://gruposaberes.co/rails_target" nsPrefix="rails">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="RailsAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataType" lowerBound="1"
        eType="#//RailsDataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RailsMethod">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="methodType" lowerBound="1"
        eType="#//RailsMethodType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RailsClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="classType" lowerBound="1"
        eType="#//RailsClassType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
        eType="#//RailsMethod" containment="true">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//RailsAttribute" containment="true">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RailsAssociation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//RailsClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//RailsClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="foreignKeyColumnName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceRoleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetRoleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceCardinality" lowerBound="1"
        eType="#//RailsCardinality"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetCardinality" lowerBound="1"
        eType="#//RailsCardinality"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="associationType" lowerBound="1"
        eType="#//RailsAssociationType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RailsNamespace">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="#//RailsClass" containment="true">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RailsApplication">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="railsAssociations" upperBound="-1"
        eType="#//RailsAssociation" containment="true">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="#//RailsClass" containment="true">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="namespaces" upperBound="-1"
        eType="#//RailsNamespace" containment="true">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RailsDataType">
    <eLiterals name="none"/>
    <eLiterals name="binary"/>
    <eLiterals name="boolean"/>
    <eLiterals name="date"/>
    <eLiterals name="datetime"/>
    <eLiterals name="decimal"/>
    <eLiterals name="float"/>
    <eLiterals name="integer"/>
    <eLiterals name="bigint"/>
    <eLiterals name="primary_key"/>
    <eLiterals name="references"/>
    <eLiterals name="string"/>
    <eLiterals name="text"/>
    <eLiterals name="time"/>
    <eLiterals name="timestamp"/>
    <eLiterals name="hstore"/>
    <eLiterals name="json"/>
    <eLiterals name="array"/>
    <eLiterals name="cidr_address"/>
    <eLiterals name="ip_address"/>
    <eLiterals name="mac_address"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RailsMethodType">
    <eLiterals name="instanceMethod"/>
    <eLiterals name="classMethod"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RailsClassType">
    <eLiterals name="none"/>
    <eLiterals name="activeRecord"/>
    <eLiterals name="activeResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RailsCardinality">
    <eLiterals name="none"/>
    <eLiterals name="one"/>
    <eLiterals name="many"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RailsAssociationType">
    <eLiterals name="aggregation"/>
    <eLiterals name="composition"/>
  </eClassifiers>
</ecore:EPackage>
