/**
 * generated by Xtext 2.10.0
 */
package co.gruposaberes.model;

import co.gruposaberes.model.AbstractRailsSchemaRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class RailsSchemaRuntimeModule extends AbstractRailsSchemaRuntimeModule {
}
