/**
 * generated by Xtext 2.10.0
 */
package co.gruposaberes.model;

import co.gruposaberes.model.RailsSchemaStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class RailsSchemaStandaloneSetup extends RailsSchemaStandaloneSetupGenerated {
  public static void doSetup() {
    RailsSchemaStandaloneSetup _railsSchemaStandaloneSetup = new RailsSchemaStandaloneSetup();
    _railsSchemaStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
